services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: maslow-app
        container_name: maslow-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: maslow-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
    dbdata:
